### PR TITLE
return data: URL unchanged

### PR DESCRIPTION
**Pull request by forresto**
useful for image upload previews

### CODE REVIEW

**Comment by paulyoung** [comment]
imgflo doesn't do anything with `data:` URLs?

**Comment by forresto** [comment]
`414 (Request-URI Too Long)` ... we're uploading the binary image at the same time.

**Comment by paulyoung** [comment]
Makes sense then I suppose :+1: 

:ship:

**Comment by forresto** [comment]
Wanna :green_heart: :point_left: and publish?

**Pull request merged**
